import assert from 'node:assert/strict';
const base='http://127.0.0.1:8787/api/game';
const client=()=>({cookie:'',async post(data,status=200){const r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://127.0.0.1:8787',Cookie:this.cookie},body:JSON.stringify(data)});const b=await r.json();assert.equal(r.status,status,JSON.stringify(b));const c=r.headers.get('set-cookie');if(c)this.cookie=c.split(';')[0];return b;},async get(status=200){const r=await fetch(base,{headers:{Cookie:this.cookie}});assert.equal(r.status,status);return r.json();}});
const teacher=client(),students=Array.from({length:6},client);
await teacher.post({action:'create',password:'classroom-test-pass'});
const room=(await teacher.get()).room.code;
await client().post({action:'login',code:room,password:'wrong'},403);
for(let i=0;i<6;i++)await students[i].post({action:'join',code:room,team:i+1});
assert.equal((await teacher.get()).teams.filter(t=>t.joined).length,6);
assert.equal((await students[0].get()).teams.length,1);
await students[0].post({action:'advance'},403);
await teacher.post({action:'advance'});
for(let i=0;i<2;i++){const r=await students[0].post({action:'answer',stage:1,answers:[0],source:'검증 자료'});assert.equal(r.correct,false);assert.equal(r.hint,i===1);}
assert.equal((await students[0].post({action:'answer',stage:1,answers:[1,4],source:'NASA와 박물관 자료'})).correct,true);
assert.deepEqual((await students[0].get()).teams[0].completed,[1]);
await teacher.post({action:'advance'});
assert.deepEqual((await students[5].get()).teams[0].completed,[1]);
for(let sub=0;sub<3;sub++)await students[0].post({action:'answer',stage:2,sub,answers:[sub===2?1:0]});
await teacher.post({action:'advance'});
await students[0].post({action:'answer',stage:2,sub:0,answers:[0]},409);
await students[0].post({action:'answer',stage:3,answers:[3]});
await teacher.post({action:'advance'});
await students[0].post({action:'answer',stage:4,answers:[2]});
await teacher.post({action:'advance'});
await students[0].post({action:'final',pin:'0000',answer:'확인해요'},400);
await students[0].post({action:'final',pin:'3729',answer:'AI가 한 말을 믿을 만한 자료로 확인하고 질문해요.'});
await teacher.post({action:'review',team:1,approved:false,feedback:'어떤 자료인지 더 적어 볼까요?'});
assert.equal((await students[0].get()).teams[0].feedback,'어떤 자료인지 더 적어 볼까요?');
await students[0].post({action:'final',pin:'3729',answer:'책과 공공기관 자료로 확인하고, AI에게 구체적으로 질문해요.'});
await teacher.post({action:'review',team:1,approved:true,feedback:'좋아요!'});
assert.equal((await students[0].get()).teams[0].approved,true);
const returning=client();await returning.post({action:'join',code:room,team:1});assert.equal((await returning.get()).teams[0].approved,true);
await teacher.post({action:'delete'});await returning.get(401);await client().post({action:'join',code:room,team:1},404);
console.log('PASS: 6팀 입장, 권한, 힌트, 정답, 전체 이동, 이어하기, 피드백, 승인, 수업 삭제');
